FROM --platform=linux/arm64v8 jarischaefer/baseimage-ubuntu:4.0-arm64v8
ADD qemu-aarch64-static /usr/bin

ARG COMPOSER_VERSION
ARG NET_IPV4_VERSION
ARG NET_IPV6_VERSION

ADD pre_install /

RUN chmod +x /build/install && /build/install && rm -r /build
